<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="5CG1265QHJ" failures="1" tests="6" name="Personal Loan" time="0.048" errors="0" timestamp="2022-02-27T08:06:22 IST">
  <testcase classname="TestPackage.Day1" name="Demo" time="0.008">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestPackage.Day1.Demo(Day1.java:20)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- Demo -->
  <testcase classname="TestPackage.Day2" name="Demo" time="0.001"/>
  <testcase classname="TestPackage.Day2" name="SecondTest" time="0.001"/>
  <testcase classname="TestPackage.Day4" name="APILoginHomeLoan" time="0.002"/>
  <testcase classname="TestPackage.Day4" name="MobileLoginHomeLoan" time="0.001"/>
  <testcase classname="TestPackage.Day4" name="WebloginHomeloan" time="0.001"/>
  <testcase classname="TestPackage.Day1" name="SecondTest" time="0.0">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal Loan -->
